version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      non-major:
        update-types:
          - minor
          - patch
      react:
        patterns:
          - react
          - react-dom
      tailwindcss:
        patterns:
          - tailwindcss
          - "@tailwindcss/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
