version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      non-major:
        update-types:
          - minor
          - patch
      react:
        patterns:
          - react
          - react-dom

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
