minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@next/*'
  - next
  - react
  - react-dom

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@tailwindcss/oxide'
  - esbuild
  - rclone.js
  - sharp
  - workerd
